### ISSUE TITLE
Building problems on CENTOS

### ISSUE THREAD

**Issue by adaviel** [HoneProject/Linux-Sensor#1]
I'm an "occasional developer" ...

Just downloaded and tried to build on CENTOS 6.2 and SL 5.2.
On 6.2 I have kernel-2.6.32-220.el6.x86_64 (and kernel-devel) and get:
socket_notify.c:109: error: too few arguments to function ‘inet_family_ops.create’
socket_lookup.h:383: error: redefinition of ‘nf_tproxy_get_sock_v6’

On 5.2  I have kernel-2.6.18-274.3.1.el5.x86_64 and get:
socket_notify.c:106: error: conflicting types for 'inet_create_hook'
and many others. Looks like the stock kernel does not have kprobes support.

What chance of building on these enterprise distros ?
